### ISSUE TITLE
ValueError: The model did not return a loss from the inputs, only the following keys: logits,past_key_values. For reference, the inputs it received are input_ids,attention_mask.

### ISSUE THREAD

**Issue by thistleknot** [princeton-nlp/MeZO#19]
Got further.  Asked chatgpt, and it pointed out there is no loss.  I see this in zo_forward

    def zo_forward(self, model, inputs):
        """
        **Get (no gradient) loss from the model. Dropout is turned off too.**
        """
        model.eval()
        if self.args.non_diff:
            # Non-differentiable objective (may require autoregressive generation)
            return self.zo_forward_nondiff(model, inputs)

        with torch.inference_mode():
            inputs = self._prepare_inputs(inputs)
            with self.compute_loss_x	context_manager():
                loss = self.compute_loss(model, inputs)
            if self.args.n_gpu > 1:
                # Warning: this is copied from the original Huggingface Trainer. Untested.
                loss = loss.mean()  # mean() to average on multi-gpu parallel training
        return loss.detach()
```
Traceback (most recent call last):
  File "/home/user/TrainLLMv2/mezo.py", line 72, in <module>
    trainer.train()
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/TrainLLMv2/functions.py", line 420, in _inner_training_loop
    tr_loss_step = self.zo_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/TrainLLMv2/functions.py", line 679, in zo_step
    loss1 = self.zo_forward(model, inputs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/TrainLLMv2/functions.py", line 632, in zo_forward
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/transformers/trainer.py", line 2692, in compute_loss
    raise ValueError(
ValueError: The model did not return a loss from the inputs, only the following keys: logits,past_key_values. For reference, the inputs it received are input_ids,attention_mask.
```

**Comment by thistleknot** [comment]
actually, this might be due to the way I'm creating my dataset... sorry about that.

**Comment by thistleknot** [comment]
this was due to my data.

Thank you for your patience, I believe I got it going =D
